apiVersion: v1
kind: Service
metadata:
  namespace: sampleapps
  name: goprometheus
spec:
  type: ClusterIP
  ports:
  - name: http 
    port: 8080
    targetPort: http 
  selector:
    app: goprometheus

---
---
apiVersion: v1
kind: Service
metadata:
  namespace: sampleapps
  name: goprometheus-service
  labels:
    prometheus: go-prometheus
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8081
      targetPort: http-metrics
  selector:
    app: goprometheus 
