apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: vote-route
  namespace: voting
spec:
  host: vote-route-voting-app.apps.homelabsno.mondeo
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: vote
    weight: 100
  wildcardPolicy: None
