<<<<<<< HEAD
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: vote-route
  namespace: voting-app
spec:
  host: vote-route-voting-app.apps.homelabsno.mondeo
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: vote
    weight: 100
  wildcardPolicy: None
=======
# Create a secure connection to the proxy via a route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: proxy
spec:
  to:
    kind: Service
    name: proxy
  tls:
    termination: Reencrypt
>>>>>>> cc13fc2afd676bfe698dd613170943e9836f1305
