FROM golang:1.19.6-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download && go mod verify

COPY main.go main.go

RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux  go build -o /myapp main.go

FROM gcr.io/distroless/base-debian11

COPY --from=build /myapp /myapp

ENTRYPOINT ["/myapp"]
